name:                arbor-monad-logger
version:             0.1.0.0
github:              "packetloop/arbor-monad-logger"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com.com"
copyright:           "2018 John Ky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/packetloop/arbor-monad-logger#readme>

dependencies:
- base >= 4.7 && < 5
- monad-logger

library:
  source-dirs: src
